COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://labolya21:21Olya0823@server-labs.mysql.database.azure.com:3306/solar_station_db?ssl=true"

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:AXProduct2024@localhost/test"

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: 210lya0822/
  SWAGGER:
    openapi: "3.0.2"
    info:
      title: "Solar Station API"
      description: |
        API documentation for the Solar Station management system.
        It allows to manage users, batteries, stations, panels, etc.
      version: "1.0.0"
      contact:
        name: "Smart Traffic Team"
        email: "team@example.com"
    servers:
      - url: "http://localhost:1401"
        description: "Local development server"
      - url: "http://172.187.202.191:1401"
        description: "Azure VM deployment"
    tags:
      - name: "battery_charge"
        description: "Endpoints related to battery charge management"
      - name: "users"
        description: "Operations related to users"
      - name: "stations"
        description: "Operations related to solar stations"
