COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
#  SQLALCHEMY_DATABASE_URI: 'sqlite://'
#  SQLALCHEMY_DATABASE_URI: 'sqlite:///device_db.sqlite'
  SQLALCHEMY_DATABASE_URI: 'mysql://root:21Olya0822/@127.0.0.1/solar_station_db3'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql://root:AXProduct2024@localhost/test'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: 21Olya0822/
