COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://labolya21:21Olya0822@server-labs.mysql.database.azure.com:3306/solar_station_db3?ssl_ca=/home/azureuser/ssl_certs/BaltimoreCyberTrustRoot.crt.pem&ssl_mode=REQUIRED"
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://{0}:{1}@server-labs.mysql.database.azure.com:3306/solar_station_db3?ssl=true"

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:AXProduct2024@localhost/test"

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: labolya21
  MYSQL_ROOT_PASSWORD: 21Olya0822
  SWAGGER:
    swagger: "2.0"
    info:
      title: "Solar Station API"
      description: "API documentation for the Solar Station management system"
      version: "1.0.0"
    basePath: "/"
    schemes:
      - "http"
    tags:
      - name: "users"
        description: "Operations related to users"
      - name: "stations"
        description: "Operations related to solar stations"
